# -*- coding: utf-8 -*-
"""helper.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SkSgOJ3zDlTlol79nzr6OM0SBGx_3Pi8
"""

import os


def load_data(path):
    """
    Load dataset
    """
    input_file = os.path.join(path)
    with open(input_file, "r") as f:
        data = f.read()

    return data.split('\n')